In [26]:
import numpy as np
import random as rr
import pandas as pd

In [27]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
np.arange(1,21,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [29]:
grades = np.arange(60,101)

In [30]:
grades

array([ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
        73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
        86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
        99, 100])

In [31]:
[rr.randrange(1,7) for i in range(0,10)]

[1, 5, 5, 6, 6, 3, 2, 4, 6, 6]

In [32]:
np.random.randint(1,7,10)

array([3, 5, 1, 3, 5, 3, 1, 5, 6, 1])

In [33]:
timeit number_list = [rr.randrange(1,7) for i in range(0, 1_000_000)]

974 ms ± 24.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [40]:
timeit number_array = np.random.randint(1,7,1_000_000)

9.37 ms ± 134 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [41]:
grades_array = np.array([87, 100, 91])

In [42]:
grades = pd.Series(grades_array, index = ['Harry', 'Hermione', 'Ron'])

In [43]:
grades

Harry        87
Hermione    100
Ron          91
dtype: int32